# Generated by Django 2.0.6 on 2018-09-04 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20180829_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=40, verbose_name='Company Name')),
                ('chamberOfCommerceNo', models.CharField(max_length=40, verbose_name='second Name')),
                ('firstName', models.CharField(max_length=40, verbose_name='First Name')),
                ('secondName', models.CharField(max_length=40, verbose_name='Second Name')),
                ('address', models.CharField(max_length=40, verbose_name='Address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('postcode', models.CharField(max_length=40, verbose_name='Postcode')),
                ('Land', models.CharField(max_length=40, verbose_name='Land')),
                ('OrderHistory', models.CharField(max_length=40, verbose_name='OrderHistory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
