# Generated by Django 2.0.6 on 2018-09-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20180928_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
