# Generated by Django 2.0.6 on 2018-10-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20181003_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
