# Generated by Django 2.0.6 on 2018-08-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=40)),
                ('fitting', models.CharField(blank=True, max_length=40, null=True)),
                ('material', models.CharField(blank=True, max_length=40, null=True)),
                ('mains', models.CharField(max_length=40)),
                ('height', models.CharField(blank=True, max_length=40, null=True)),
                ('width', models.CharField(blank=True, max_length=40, null=True)),
                ('diameter', models.CharField(blank=True, max_length=40, null=True)),
                ('colour', models.CharField(blank=True, max_length=40, null=True)),
                ('art_No', models.CharField(max_length=40)),
                ('bruto_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transformer_included', models.BooleanField(default=True)),
                ('product_type', models.CharField(max_length=15)),
                ('miscellaneous', models.TextField()),
            ],
        ),
    ]
