# Generated by Django 2.0.6 on 2018-08-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180829_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fitting',
            field=models.CharField(blank=True, choices=[('E27', 'E27'), ('E16', '16'), ('GU10', 'GU10')], default='Fitting', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('X', 'choose type'), ('suspension', 'suspension'), ('floor', 'floor'), ('table', 'table'), ('wall/ceiling', 'wall/ceiling'), ('outside', 'outside')], default='Product type', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('X', 'choose material'), ('metal sprayed copper', 'metal sprayed copper'), ('metal sprayed silver', 'metal sprayed silver'), ('aluminium', 'Abstract'), ('copper', 'copper')], default='Material', max_length=40, null=True),
        ),
    ]
