# Generated by Django 2.0.6 on 2018-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180911_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fitting',
            field=models.CharField(blank=True, choices=[('X', 'choose fitting'), ('E27', 'E27'), ('E16', '16'), ('GU10', 'GU10'), ('T5', 'T5'), ('LED built in', 'LED built in')], default='X', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('X', 'choose material'), ('metal sprayed copper', 'metal sprayed copper'), ('metal sprayed silver', 'metal sprayed silver'), ('metal', 'metal'), ('aluminium', 'aluminium'), ('copper', 'copper'), ('vineer', 'vineer'), ('fibreglass', 'fibreglass')], default='X', max_length=40, null=True),
        ),
    ]
