# Generated by Django 2.0.6 on 2018-08-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180829_1246'),
        ('products', '0004_auto_20180829_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='accounts.Brand'),
            preserve_default=False,
        ),
    ]
