# Generated by Django 2.0.6 on 2018-09-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180911_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='product_id',
        ),
    ]
