# Generated by Django 2.0.6 on 2018-09-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180903_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='fitting',
            field=models.CharField(blank=True, choices=[('X', 'fitting'), ('E27', 'E27'), ('E16', '16'), ('GU10', 'GU10'), ('LED built in', 'LED built in')], default='X', max_length=40, null=True),
        ),
    ]
